apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresInit.configMapName }}
  labels:
    {{- include "gratitudeapp.labels" . | nindent 4 }}
data:
  001-create-moods.sql: |
{{ .Values.postgresInit.createMoodsSql | indent 4 }}
